name: google_maps_flutter_floating_marker_titles
description: Floating Map Marker Titles for google_maps_flutter
version: 0.0.3+3
repository: https://github.com/androidseb/flutter_map_floating_marker_titles

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  latlong: ^0.6.1

  flutter_floating_map_marker_titles_core: ^0.0.3+3
  google_maps_flutter: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
