name: google_maps_flutter_floating_marker_titles
description: Floating Map Marker Titles for google_maps_flutter
version: 1.0.0
repository: https://github.com/androidseb/flutter_map_floating_marker_titles

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  latlong2: ^0.9.0

  #flutter_floating_map_marker_titles_core: ^1.0.0
  # Uncomment and use this a dependency when working locally
  #flutter_floating_map_marker_titles_core:
  #  path: ../flutter_floating_map_marker_titles_core
  google_maps_flutter: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: 2.1.2
