name: flutter_floating_map_marker_titles_demo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Specifying the version 2.0.4 so that we remain compatible with Android API level 16 instead of 20.
  # Version 2.0.5 of google_maps_flutter makes the minimum SDK version of Android apps 20.
  # See changelog for details:
  # https://pub.dev/packages/google_maps_flutter/changelog
  google_maps_flutter: 2.0.4

# Dependency overrides for the demo app, you would normally use this in dependencies:
#  flutter_floating_map_marker_titles_core: ^X.Y.Z+1
#  flutter_map_floating_marker_titles: ^X.Y.Z+1
#  google_maps_flutter_floating_marker_titles: ^X.Y.Z+1
dependency_overrides:
  flutter_floating_map_marker_titles_core:
    path: ../flutter_floating_map_marker_titles_core
  flutter_map_floating_marker_titles:
    path: ../flutter_map_floating_marker_titles
  google_maps_flutter_floating_marker_titles:
    path: ../google_maps_flutter_floating_marker_titles

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/marker.png
