name: flutter_floating_map_marker_titles_core
description: Flutter Floating Map Marker Titles Core library
version: 1.0.0
repository: https://github.com/androidseb/flutter_map_floating_marker_titles

environment:
  sdk: '>=2.17.1 <3.0.0'
  # This flutter >= 2.8.0 requirement is necessary for the web implementation to work:
  # https://github.com/flutter/flutter/issues/46683
  flutter: '>=2.8.0'

dependencies:
  flutter:
    sdk: flutter
  latlong2: ^0.9.0
  meta: ^1.7.0
  proj4dart: ^2.0.0
  tuple: ^2.0.0
  vector_math: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: 2.1.2
