name: flutter_floating_map_marker_titles_core
description: Flutter Floating Map Marker Titles Core library
version: 0.0.3+3
repository: https://github.com/androidseb/flutter_map_floating_marker_titles

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  tuple: ^2.0.0
  vector_math: ^2.1.0
  proj4dart: ^2.0.0
  meta: ^1.7.0
  latlong2: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
