name: flutter_map_floating_marker_titles
description: Floating Map Marker Titles for flutter_map
version: 0.0.1+1
repository: https://github.com/androidseb/flutter_map_floating_marker_titles

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  latlong: ^0.6.1

  flutter_floating_map_marker_titles_core: ^0.0.2+2
  flutter_map: ^0.10.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
