name: flutter_map_floating_marker_titles
description: Floating Map Marker Titles for flutter_map
version: 0.3.0
repository: https://github.com/androidseb/flutter_map_floating_marker_titles

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  latlong2: ^0.8.1

  flutter_floating_map_marker_titles_core: ^0.3.0
  # Uncomment and use this a dependency when working locally
  #flutter_floating_map_marker_titles_core:
  #  path: ../flutter_floating_map_marker_titles_core
  flutter_map: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
