name: flutter_map_floating_marker_titles
description: Floating Map Marker Titles for flutter_map
version: 0.0.5+5
repository: https://github.com/androidseb/flutter_map_floating_marker_titles

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  latlong2: ^0.8.1

  flutter_floating_map_marker_titles_core: ^0.0.5+5
  # Uncomment and use this a dependency when working locally
  #flutter_floating_map_marker_titles_core:
  #  path: ../flutter_floating_map_marker_titles_core
  flutter_map: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
